version: '3.8'

x-heroku: &heroku
  image: tps-snipe-it:heroku
  env_file:
    - .env-default
    - .env
  volumes:
    - ./docker-compose:/docker-compose

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: snipeit
    ports:
      - "13306:3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:latest

  postdeploy:
    <<: *heroku
    build:
      context: ..
      dockerfile: Dockerfile.tps
    command: /docker-compose/postdeploy.sh

  release:
    <<: *heroku
    depends_on:
      - postdeploy
    command: /docker-compose/release.sh

  web:
    <<: *heroku
    depends_on:
      - postdeploy
    environment:
      PORT: 3051
    ports:
      - 3051:3051
    command: /docker-compose/web.sh

volumes:
  mysql:
  vendor:
